### ISSUE TITLE
What is an exact definition of iterators

### ISSUE THREAD

**Issue by msurkovsky** [spirali/qit#2]
Can you write up an exact definition how the iterators should work, please? What's the interface, what is expected, how the obligatory method should work, and so forth. My motivation: If I have an array of values of one specific type, is it ok to have only one iterator of this type and use it for all values? If so, the next method of rage iterator is wrong written. If not, I don't see any problem to return current value of iterator.

If the iterators must not contain any inner value and one iterator for one type is enough. I will rewrite the mapping once again :)

**Comment by spirali** [comment]
I do not understand your question. Let me repeat that the following test that should passed:

```python
m = Mapping(Range(2), Range(2))
result = Qit().run(m.iterate())
expected =  [{0: 0, 1: 0}, {0: 0, 1: 1}, {0: 1, 1: 0}, {0: 1, 1: 1}]
assert set(result) == set(expected)
```

I hope that it answers your question.

**Comment by msurkovsky** [comment]
Sorry but no. Firstly, your test should pass; the only problem could be that expected array should look (or it is implemented) like this: [[(0,0), (1,0)], [(0, 0), (1,1)], ...]. Secondly, I've spoke about cpp implementation. Look carefully at next in range.h. here is an inner value which is incremented and this value is assigned to the out one. If I understand it correctly, the provided out value should be incremented directly. So there is no reason to keep any inner value.

**Comment by Kobzol** [comment]
But the range needs to know when to stop, the outer value can be arbitrary and doesn't need to start at  the range minimum and stop at the range maximum.

**Comment by msurkovsky** [comment]
But I didn't spoke about stop criteria. That's ok. Here is how I think it should work:
```c++
bool next(value_type &out) {
    if (out == stop) {
	return false;
    }
    out++
    return true;
}
```

**Comment by Kobzol** [comment]
Sorry, I understand now :-) Yes, that should probably be enough, even though I'm not sure whether the out value is required to have the old value (maybe it could be reinitialized or reused in a different context between two calls to Range::next?). But for the simple cases this should be enough. Still I don't see it as a problem to keep the counter in the range, that won't probably hurt performance so much :-)

**Comment by msurkovsky** [comment]
It's not about performance but semantics of iterators. Because in the current implementation if I had an array of integers and consider them as values for iterator, e.g. range(4), then I have to have one iterator for each value, because it has inner state. Without this inner state I could use one iterator for all values. And that was what I wanted Standa to clearly state the semantics of iterators -- C++ iterators.

**Comment by spirali** [comment]
I am closing this issue, because the implementation of iterators has been completely changed.
